# Generated by Django 5.0.7 on 2024-07-14 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='apikey',
            name='revoked',
        ),
    ]
